name: Update Raspberry Pi on Commit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Deploy to Raspberry Pi
      uses: xtellurian/ssh-deploy@v2.3.3
      with:
        ssh-private-key: ${{ secrets.PI_SSH_KEY }}
        args: "cd /home/pi/Alert && git pull && npm install && npm run build && pm2 restart all"
